---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 1m
  releaseName: external-dns
  targetNamespace: kube-system
  chart:
    spec:
      chart: external-dns
      version: "1.3.2"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  valuesFrom:
  - kind: ConfigMap
    name: helm-external-dns
    valuesKey: values.yaml