---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-autoscaler
  namespace: flux-system
data:
  values.yaml: |
    autoDiscovery:
      clusterName: revolut
    rbac:
      create: true
      pspEnabled: true
      serviceAccount:
        create: true
        name: cluster-autoscaler
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::356003666994:role/revolut-eks-cluster-autoscaler