---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: autoscaler
  namespace: flux-system
spec:
  interval: 1m
  releaseName: autoscaler
  targetNamespace: kube-system
  chart:
    spec:
      chart: cluster-autoscaler
      version: "9.10.7"
      sourceRef:
        kind: HelmRepository
        name: autoscaler
        namespace: flux-system
  valuesFrom:
  - kind: ConfigMap
    name: helm-autoscaler
    valuesKey: values.yaml