apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: revolut
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kubernetes/
  prune: true
  sourceRef:
    kind: GitRepository
    name: revolut
  validation: client