---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-aws-load-balancer-controller
  namespace: flux-system
data:
  values.yaml: |
    clusterName: revolut
    ingressClass: alb
    hostNetwork: true

    image:
      repository: 602401143452.dkr.ecr.us-west-1.amazonaws.com/amazon/aws-load-balancer-controller

    serviceAccount:
      create: true
      name: aws-load-balancer-controller
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::660510932689:role/revolut-eks-aws-load-balancer-controller

    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi