name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: pytester-cov
        uses: alexanderdamiani/pytester-cov@v1.2.1
        with:
          pytest-root-dir: . 
          pytest-tests-dir: app/ # optional, default is 
          cov-omit-list: integration-tests/
          requirements-file: app/requirements.txt

 
